### PR TITLE
Import reference Compare fix

### PR DESCRIPTION
**Pull request by Ashersam**
Fix for import reference compare with translation for all languages with a precise count of addition and deletion #125 test and working

### CODE REVIEW

**Comment by hanokkurian** [comment]
> Fix for import reference compare with translation for all languages with a precise count of addition and deletion #125 test and working

Still not working in Autographa Lite 1.3.1

**Comment by joelthe1** [comment]
Can you provide the steps the reproduce the issue on our side? Also, any screenshots?

**Comment by hanokkurian** [comment]
Autographa-1
Autographa-2
Autographa-3
Autographa-4
Autographa-4b
Autographa-5

**Comment by joelthe1** [comment]
Thanks @hanokkurian! As an initial check to rule out issues due to previous data, can you:

**Comment by joelthe1** [comment]
This was fixed via #142 and available from [v1.3.2](https://github.com/friendsofagape/autographa-lite/releases/tag/v1.3.2)

**Pull request merged**
