### PR TITLE
line break with m-tag

### PR DESCRIPTION
**Pull request by Ashersam**
Preserve the newline while import and export usfm newline with `m-tag`.
And also preserve newline on all HTML export #155

### CODE REVIEW

**Comment by Ashersam** [comment]
> I'd like to see a demo.

Yes, we need to have a short discussion.

**Comment by joelthe1** [comment]
There are conflicts on this PR now. Also, did you test on Windows?

**Comment by Ashersam** [comment]
> There are conflicts on this PR now. Also, did you test on Windows?

yes tested with windows

**Comment by Ashersam** [comment]
Yes, conflicts were expected since the same files. But different lines

**Pull request closed without merging**
