### PR TITLE
Updated React to 16.8.1

### PR DESCRIPTION
**Pull request by Ashersam**
Updated react to 16.8.1 (#84 ) along some other packages and made necessary changes in the test cases

### CODE REVIEW

**Comment by joelthe1** [comment]
Please confirm test case run.

**Comment by joelthe1** [comment]
Please re-run test cases and update changes.

**Comment by Ashersam** [comment]
> Please re-run test cases and update changes.
Test cases run successfully
Sandeep will push the code to the new branch as it branch conflicts

**Comment by joelthe1** [comment]
Changes are deprecated.

**Pull request closed without merging**
